name: Release

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.3.4, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, intl

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --dev

      - name: Run Pest Tests (optional)
        run: ./vendor/bin/pest --min=80

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
